# Generated by Django 5.0.7 on 2024-10-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cover_one', '0004_alter_two_d_cover_cover_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='two_d_cover',
            new_name='cover_one',
        ),
    ]
